const data = {
    users: [
        {username: "Alice", password: "alice123", admin: true, saved: ["Into the Spider-Verse", "John Wick", "Hot Fuzz"] },
        {username: "Bob", password: "bob123", admin: false, saved: ["Pulp Fiction", "Deadpool", "1917"] },
        {username: "Charlie", password: "charlie123", admin: false, saved: ["Avatar: Fire and Ash", "Central Intelligence", "The Interview"] },
        {username: "Diana", password: "diana123", admin: false, saved: ["Dungeons & Dragons", "Into the Spider-Verse", "Deadpool"] },
        {username: "jeff", password: "jeff", admin: true, saved: ["John Wick", "Central Intelligence", "1917"] }
    ],

    movies: [
        {title: "Into the Spider-Verse", 
            genre: ["Action", "Animation", "Comedy"], 
            img: "https://via.placeholder.com/300x450?text=Into+the+Spider-Verse", 
            description: "Um jovem Spider-Man descobre o multiverso e encontra outras versões do herói, numa aventura animada cheia de ação e humor.", 
            fullDescription: "Miles Morales, um jovem adolescente que recentemente ganhou poderes de aranha, descobre que existe um multiverso repleto de outras versões do Spider-Man. Quando uma ameaça cósmica coloca todos os universos em risco, Miles deve unir-se com outras versões do herói para salvar não apenas o seu mundo, mas todo o multiverso. Uma aventura animada visualmente deslumbrante, repleta de ação, humor e momentos emocionantes que exploram temas de responsabilidade e identidade.", 
            platforms: ["Netflix", "Amazon Prime Video", "Disney+"],
            top: true},
        {title: "The Interview", 
            genre: ["Comedy", "Drama", "Thriller"], 
            img: "https://via.placeholder.com/300x450?text=The+Interview", 
            description: "Dois jornalistas recebem a missão impossível de entrevistar o líder da Coreia do Norte, misturando comédia e suspense político.", 
            fullDescription: "Dave Skylark, um apresentador de talk show superficial, e seu produtor Aaron Rapoport recebem uma oportunidade inesperada: entrevistar o ditador norte-coreano Kim Jong-un. O que começa como uma viagem comedida torna-se uma missão de espionagem da CIA, colocando os dois amigos em perigo iminente. O filme combina humor irreverente com a tensão de uma situação política delicada, criando uma comédia de ação que brinca com questões internacionais enquanto mantém o foco na amizade entre os dois protagonistas.", 
            platforms: ["Netflix", "Google Play", "YouTube"],
            top: false},
        {title: "Pulp Fiction", 
            genre: ["Crime", "Drama", "Thriller"], 
            img: "https://via.placeholder.com/300x450?text=Pulp+Fiction", 
            description: "Histórias interligadas de crime, vingança e humor negro em Los Angeles, clássico de Tarantino com diálogos memoráveis.", 
            fullDescription: "Uma obra-prima do cinema que entrelaça múltiplas histórias de criminosos, boxeadores, gangsters e assassinos em Los Angeles. O filme de Quentin Tarantino é conhecido pelos seus diálogos brilhantes, humor negro, violência estilizada e estrutura não-linear que revolucionou o cinema de ação. Com um elenco icónico e sequências memoráveis, Pulp Fiction explora temas de lealdade, redenção e consequências das escolhas, tudo isso enquanto mantém uma energia frenética e uma atmosfera única que influenciou gerações de cineastas.", 
            platforms: ["Netflix", "Disney+", "Amazon Prime Video"],
            top: true},
        {title: "John Wick", 
            genre: ["Action", "Crime", "Thriller"], 
            img: "https://via.placeholder.com/300x450?text=John+Wick", 
            description: "Ex-assassino volta à ação para vingar a morte do seu cão, iniciando uma onda de violência estilizada e épica.", 
            fullDescription: "John Wick é um ex-assassino de elite que se reformou e desejava apenas uma vida pacífica. Quando criminosos invadem a sua casa e matam o seu cão - um presente de despedida da sua falecida esposa - Wick é forçado a sair da aposentadoria. Determinado a vingar-se, ele embarca numa jornada de destruição pura, enfrentando facções criminosas inteiras. O filme é celebrado pela sua coreografia de ação impecável, utilização criativa do ambiente para combate, e a construção de um universo criminal complexo. Keanu Reeves entrega uma performance silenciosa mas poderosa, tornando este na definição moderna do thriller de ação.", 
            platforms: ["Netflix", "Amazon Prime Video", "Hulu"],
            top: true},
        {title: "Hot Fuzz", 
            genre: ["Comedy", "Action", "Mystery"], 
            img: "https://via.placeholder.com/300x450?text=Hot+Fuzz", 
            description: "Um policial exemplar é transferido para uma pacata vila inglesa, mas descobre conspirações e assassinatos num tom de comédia afiada.", 
            fullDescription: "Nicholas Angel é um polícia super-eficiente de Londres que é transferido para a pequena e aparentemente tranquila vila de Sandleford. Inicialmente frustrado com a transferência e a falta de criminalidade, Angel começa a notar estranhas coincidências de mortes que as autoridades locais parecem ignorar deliberadamente. Juntamente com o seu colega constável bem-intencionado, Angel desvenda uma conspiração surpreendente envolvendo os cidadãos respeitáveis da vila. A comédia brilhante de Edgar Wright combina referências pop culture, ação extravagante e humor britânico astuto, resultando numa sátira perspicaz sobre tradições comunitárias e conformismo.", 
            platforms: ["Netflix", "Amazon Prime Video", "hbo"],
            top: false},
        {title: "Avatar: Fire and Ash", 
            genre: ["Action", "Adventure", "Sci-Fi"], 
            img: "https://via.placeholder.com/300x450?text=Avatar+Fire+and+Ash", 
            description: "Nova saga de ação e aventura num mundo alienígena vibrante, onde batalhas épicas definem o destino de Pandora.", 
            fullDescription: "A continuação épica da saga Avatar leva-nos novamente para o mundo de Pandora, onde novas ameaças e novos mundos aguardam. As tribos Na'vi enfrentam novos invasores com tecnologia avançada, enquanto batalhas monumentais testam a lealdade, coragem e determinação dos personagens. O filme expande o universo visual de Pandora com novos ambientes deslumbrantes, criaturas exóticas e tecnologia futurista. Com sequências de ação de tirar o fôlego, emoção épica e um compromisso renovado com a preservação do mundo natural, Avatar: Fire and Ash continua a explorar temas de colonialismo, ecologia e resistência numa escala verdadeiramente cinematográfica.", 
            platforms: ["Disney+", "Amazon Prime Video", "Apple TV+"],
            top: true},
        {title: "Dungeons & Dragons", 
            genre: ["Fantasy", "Adventure", "Action"], 
            img: "https://via.placeholder.com/300x450?text=Dungeons+and+Dragons", 
            description: "Aventura fantástica repleta de magia, monstros e heróis improváveis numa jornada épica pelo reino de D&D.", 
            fullDescription: "Um grupo improvável de aventureiros - um ladino desastrado, um clérigo duvidoso, um bardo sedutor e um guerreiro relutante - é reunido por acaso e vê-se envolvido numa jornada épica para salvar um reino fantástico. Enfrentando dragões antigos, magias poderosas, traições inesperadas e perigos inimagináveis, este bando de heróis improvável deve aprender a trabalhar em conjunto para ter uma hipótese de sucesso. Repleta de humor, ação coreografada impressivamente, criaturas místicas e um mundo vasto repleto de magia e mistério, a aventura é uma celebração do espírito do jogo de role-playing que a inspirou, oferecendo entretenimento épico e momentos inesquecíveis.", 
            platforms: ["Netflix", "Amazon Prime Video", "Paramount+"],
            top: false},
        {title: "Deadpool", 
            genre: ["Action", "Comedy", "Superhero"], 
            img: "https://via.placeholder.com/300x450?text=Deadpool", 
            description: "Anti-herói irreverente quebra a quarta parede enquanto luta contra vilões, com muita acção e comédia sarcástica.", 
            fullDescription: "Wade Wilson, um ex-soldado com poderes de cura acelerada, torna-se o anti-herói conhecido como Deadpool. Obcecado com reconciliar-se com a sua antiga namorada Vanessa e determinado a derrotar o vilão responsável pela sua transformação, Deadpool embarque numa jornada alucinante repleta de violência criativa, humor sarcástico e auto-referência constante. O filme quebra convenções comummente associadas aos filmes de super-heróis, com Deadpool a dirigir-se regularmente ao público enquanto comete carnificina hilariante. Combinando sequências de ação coreografadas de forma inteligente, diálogos espirituosos e uma perspetiva irreverente e desrespeitosa, Deadpool é uma refrescante e libertadora entrada no género de super-heróis que prova que a comédia e a ação podem coexistir harmoniosamente.", 
            platforms: ["Disney+", "Netflix", "Amazon Prime Video"],
            top: true},
        {title: "Central Intelligence", 
            genre: ["Comedy", "Action", "Adventure"], 
            img: "https://via.placeholder.com/300x450?text=Central+Intelligence", 
            description: "Dois amigos de infância tornam-se improváveis espiões, num filme cheio de ação, comédia e confusões globais.", 
            fullDescription: "Calvin Phillips era o nerd preferido dos seus colegas na escola secundária, enquanto que Bob Stone era a estrela do futebol. Vinte anos depois, Calvin é um contador entediado e Bob é um agente da CIA encoberto que procura o seu antigo amigo para ajudar numa perigosa missão internacional. Arrastado contra a sua vontade para o mundo do espionagem, Cal vê-se envolvido em confusões globais, perseguições cinematográficas, traições inesperadas e momentos de ação intensa. O filme funciona tanto como uma comédia de amizade toque quanto como um thriller de ação legítimo, explorando temas de identidade, amizade e como as pessoas mudaram desde os seus dias de escola enquanto oferecia entretenimento rápido paced e hilarante.", 
            platforms: ["Netflix", "Amazon Prime Video", "Warner Bros Discovery"],
            top: false},
        {title: "1917", 
            genre: ["War", "Drama", "History"], 
            img: "https://via.placeholder.com/300x450?text=1917", 
            description: "Durante a Primeira Guerra Mundial, dois soldados recebem uma missão quase impossível, numa narrativa tensa e visualmente impressionante.", 
            fullDescription: "Dois soldados britânicos rasos são encarregados de uma missão praticamente suicida durante a Primeira Guerra Mundial: atravessar o terreno de ninguém e entregar uma mensagem crucial que cancela um ataque ofensivo que resultaria em centenas de mortes. Viajando com apenas um rifle, uma pistola e alguma sorte, os soldados devem navegar por trincheiras destroçadas, campos minados, florestas ardentes e confrontos com forças inimigas. O filme revolucionário de Sam Mendes é filmado de forma a parecer uma única tomada contínua, criando uma sensação imersiva e claustrofóbica de urgência. Através de cinematografia deslumbrante, design de produção meticulous e performances subtis mas poderosas, 1917 oferece uma meditação visceral e emocionante sobre os horrores da guerra, o sacrifício e a humanidade em circunstâncias extremas.", 
            platforms: ["Netflix", "Amazon Prime Video", "Apple TV+"],
            top: true}
    ],
    platforms: [
        { name: "Netflix", img: "img/logos/netflix.png", link: "https://www.netflix.com" },
        { name: "Amazon Prime Video", img: "img/logos/amazon.png", link: "https://www.primevideo.com" },
        { name: "Disney+", img: "img/logos/disney.webp", link: "https://www.disneyplus.com" },
        { name: "Google Play", img: "img/logos/google-play.avif", link: "https://play.google.com/store/movies" },
        { name: "YouTube", img: "img/logos/youtube.avif", link: "https://www.youtube.com" },
        { name: "Hulu", img: "img/logos/hulu.webp", link: "https://www.hulu.com" },
        { name: "HBO", img: "img/logos/hbo.png", link: "https://www.hbomax.com" },
        { name: "Apple TV+", img: "img/logos/apple-tv-plus.png", link: "https://tv.apple.com" },
        { name: "Paramount+", img: "img/logos/paramount.png", link: "https://www.paramountplus.com" },
        { name: "Warner Bros Discovery", img: "img/logos/warner-bros.jpg", link: "https://www.wbd.com" }
    ]
};
"crime , drama , thriller , action , animation , comedy , mystery , adventure , sci-fi , fantasy , superhero , war , history"

export default data;