const data = {
    users: [
        {username: "Alice", password: "alice123", admin: true, saved: ["Into the Spider-Verse", "John Wick", "Hot Fuzz"] },
        {username: "Bob", password: "bob123", admin: false, saved: ["Pulp Fiction", "Deadpool", "1917"] },
        {username: "Charlie", password: "charlie123", admin: false, saved: ["Avatar: Fire and Ash", "Central Intelligence", "The Interview"] },
        {username: "Diana", password: "diana123", admin: false, saved: ["Dungeons & Dragons", "Into the Spider-Verse", "Deadpool"] },
        {username: "jeff", password: "jeff", admin: true, saved: ["John Wick", "Central Intelligence", "1917"] }
    ],

    movies: [
        {title: "Into the Spider-Verse", 
            genre: ["Action", "Animation", "Comedy"], 
            img: "img/movies/spider-verse-poster.jpg", 
            description: "A young Spider-Man discovers the multiverse and encounters other versions of the hero in an animated adventure filled with action and humor.", 
            fullDescription: "Miles Morales, a teenage boy who recently gained spider powers, discovers that a multiverse exists filled with other versions of Spider-Man. When a cosmic threat puts all universes at risk, Miles must team up with other versions of the hero to save not only his world but the entire multiverse. A visually stunning animated adventure, packed with action, humor, and emotional moments that explore themes of responsibility and identity.", 
            platforms: ["Netflix", "Amazon Prime Video", "Disney+"],
            top: true},
        {title: "The Interview", 
            genre: ["Comedy", "Drama", "Thriller"], 
            img: "img/movies/the-interview.jpg", 
            description: "Two journalists receive an impossible mission to interview the leader of North Korea, blending comedy and political suspense.", 
            fullDescription: "Dave Skylark, a shallow talk show host, and his producer Aaron Rapoport receive an unexpected opportunity: to interview North Korean dictator Kim Jong-un. What begins as a straightforward trip becomes a CIA espionage mission, putting the two friends in imminent danger. The film combines irreverent humor with the tension of a delicate political situation, creating an action-comedy that plays with international issues while keeping the focus on the friendship between the two protagonists.", 
            platforms: ["Netflix", "Google Play", "YouTube"],
            top: false},
        {title: "Pulp Fiction", 
            genre: ["Crime", "Drama", "Thriller"], 
            img: "img/movies/pulp-fiction.jpg", 
            description: "Interconnected stories of crime, revenge, and dark humor in Los Angeles, a Tarantino classic with memorable dialogue.", 
            fullDescription: "A masterpiece of cinema that weaves together multiple stories of criminals, boxers, gangsters, and assassins in Los Angeles. Quentin Tarantino's film is known for its brilliant dialogue, dark humor, stylized violence, and non-linear structure that revolutionized action cinema. With an iconic cast and memorable sequences, Pulp Fiction explores themes of loyalty, redemption, and the consequences of choices, all while maintaining frenetic energy and a unique atmosphere that influenced generations of filmmakers.", 
            platforms: ["Netflix", "Disney+", "Amazon Prime Video"],
            top: true},
        {title: "John Wick", 
            genre: ["Action", "Crime", "Thriller"], 
            img: "img/movies/John Wick.jpg", 
            description: "A retired assassin returns to action to avenge his dog's death, unleashing a wave of stylized and epic violence.", 
            fullDescription: "John Wick is a retired elite assassin who wanted nothing more than a peaceful life. When criminals break into his home and kill his dog - a parting gift from his late wife - Wick is forced out of retirement. Determined for revenge, he embarks on a journey of pure destruction, facing entire criminal factions. The film is celebrated for its impeccable action choreography, creative use of environment for combat, and the construction of a complex criminal universe. Keanu Reeves delivers a silent but powerful performance, making this the modern definition of an action thriller.", 
            platforms: ["Netflix", "Amazon Prime Video", "Hulu"],
            top: true},
        {title: "Hot Fuzz", 
            genre: ["Comedy", "Action", "Mystery"], 
            img: "img/movies/hot-fuzz.jpg", 
            description: "An exemplary police officer is transferred to a quiet English village but discovers conspiracies and murders in a sharp comedic tone.", 
            fullDescription: "Nicholas Angel is a super-efficient London police officer who is transferred to the small and seemingly peaceful village of Sandleford. Initially frustrated with the transfer and lack of crime, Angel begins to notice strange coincidences of deaths that local authorities seem to deliberately ignore. Along with his well-meaning constable colleague, Angel uncovers a surprising conspiracy involving the village's respectable citizens. Edgar Wright's brilliant comedy combines pop culture references, extravagant action, and sharp British humor, resulting in an insightful satire about community traditions and conformism.", 
            platforms: ["Netflix", "Amazon Prime Video", "hbo"],
            top: false},
        {title: "Avatar: Fire and Ash", 
            genre: ["Action", "Adventure", "Sci-Fi"], 
            img: "img/movies/fire-and-ash.jpg", 
            description: "A new action-adventure saga in a vibrant alien world where epic battles define the fate of Pandora.", 
            fullDescription: "The epic continuation of the Avatar saga takes us once again to the world of Pandora, where new threats and new worlds await. The Na'vi tribes face new invaders with advanced technology, while monumental battles test the loyalty, courage, and determination of the characters. The film expands Pandora's visual universe with stunning new environments, exotic creatures, and futuristic technology. With breathtaking action sequences, epic emotion, and a renewed commitment to preserving the natural world, Avatar: Fire and Ash continues to explore themes of colonialism, ecology, and resistance on a truly cinematic scale.", 
            platforms: ["Disney+", "Amazon Prime Video", "Apple TV+"],
            top: true},
        {title: "Dungeons & Dragons", 
            genre: ["Fantasy", "Adventure", "Action"], 
            img: "img/movies/dnd.jpg", 
            description: "A fantastic adventure filled with magic, monsters, and unlikely heroes on an epic journey through the D&D realm.", 
            fullDescription: "An unlikely group of adventurers - a clumsy rogue, a skeptical cleric, a charming bard, and a reluctant warrior - are brought together by chance and find themselves involved in an epic quest to save a fantasy kingdom. Facing ancient dragons, powerful magic, unexpected betrayals, and unimaginable dangers, this ragtag band of heroes must learn to work together to have any chance of success. Filled with humor, impressively choreographed action, mystical creatures, and a vast world full of magic and mystery, the adventure is a celebration of the spirit of the role-playing game that inspired it, offering epic entertainment and unforgettable moments.", 
            platforms: ["Netflix", "Amazon Prime Video", "Paramount+"],
            top: false},
        {title: "Deadpool", 
            genre: ["Action", "Comedy", "Superhero"], 
            img: "img/movies/deadpool.jpg", 
            description: "An irreverent anti-hero breaks the fourth wall while fighting villains, with plenty of action and sarcastic comedy.", 
            fullDescription: "Wade Wilson, a former soldier with accelerated healing powers, becomes the anti-hero known as Deadpool. Obsessed with reconciling with his former girlfriend Vanessa and determined to defeat the villain responsible for his transformation, Deadpool embarks on a wild journey filled with creative violence, sarcastic humor, and constant self-reference. The film breaks conventions commonly associated with superhero movies, with Deadpool regularly addressing the audience while committing hilarious carnage. Combining intelligently choreographed action sequences, witty dialogue, and an irreverent and disrespectful perspective, Deadpool is a refreshing and liberating entry into the superhero genre that proves comedy and action can coexist harmoniously.", 
            platforms: ["Disney+", "Netflix", "Amazon Prime Video"],
            top: true},
        {title: "Central Intelligence", 
            genre: ["Comedy", "Action", "Adventure"], 
            img: "img/movies/CI.jpg", 
            description: "Two childhood friends become unlikely spies in a film filled with action, comedy, and global mishaps.", 
            fullDescription: "Calvin Phillips was the favorite nerd of his high school classmates, while Bob Stone was the football star. Twenty years later, Calvin is a bored accountant and Bob is an undercover CIA agent who seeks his old friend to help on a dangerous international mission. Reluctantly dragged into the world of espionage, Cal finds himself involved in global mishaps, cinematic chase sequences, unexpected betrayals, and intense action moments. The film works both as a touching friendship comedy and as a legitimate action thriller, exploring themes of identity, friendship, and how people have changed since their school days while delivering fast-paced and hilarious entertainment.", 
            platforms: ["Netflix", "Amazon Prime Video", "Warner Bros Discovery"],
            top: false},
        {title: "1917", 
            genre: ["War", "Drama", "History"], 
            img: "img/movies/1917.jpg", 
            description: "During World War I, two soldiers receive an almost impossible mission in a tense and visually stunning narrative.", 
            fullDescription: "Two young British soldiers are tasked with a practically suicidal mission during World War I: cross no man's land and deliver a crucial message that will cancel an offensive attack that would result in hundreds of deaths. Traveling with only a rifle, a pistol, and some luck, the soldiers must navigate through destroyed trenches, minefields, burning forests, and confrontations with enemy forces. Sam Mendes' revolutionary film is shot to appear as one continuous take, creating an immersive and claustrophobic sense of urgency. Through stunning cinematography, meticulous production design, and subtle yet powerful performances, 1917 offers a visceral and emotional meditation on the horrors of war, sacrifice, and humanity in extreme circumstances.", 
            platforms: ["Netflix", "Amazon Prime Video", "Apple TV+"],
            top: true}
    ],
    platforms: [
        { name: "Netflix", img: "img/logos/netflix.png", link: "https://www.netflix.com" },
        { name: "Amazon Prime Video", img: "img/logos/amazon.png", link: "https://www.primevideo.com" },
        { name: "Disney+", img: "img/logos/disney.webp", link: "https://www.disneyplus.com" },
        { name: "Google Play", img: "img/logos/google-play.avif", link: "https://play.google.com/store/movies" },
        { name: "YouTube", img: "img/logos/youtube.avif", link: "https://www.youtube.com" },
        { name: "Hulu", img: "img/logos/hulu.webp", link: "https://www.hulu.com" },
        { name: "HBO", img: "img/logos/hbo.png", link: "https://www.hbomax.com" },
        { name: "Apple TV+", img: "img/logos/apple-tv-plus.png", link: "https://tv.apple.com" },
        { name: "Paramount+", img: "img/logos/paramount.png", link: "https://www.paramountplus.com" },
        { name: "Warner Bros Discovery", img: "img/logos/warner-bros.jpg", link: "https://www.wbd.com" }
    ]
};
"crime , drama , thriller , action , animation , comedy , mystery , adventure , sci-fi , fantasy , superhero , war , history"

export default data;